version: "3.9"

services:

  postgres:
    image: "postgres:14"
    container_name: "userdb"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user_service
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=userdb
